### ISSUE TITLE
Keine Daten angezeigt 

### ISSUE THREAD

**Issue by PiotRe36** [andre0707/WorkoutMap#1]
Es wird leider nix angezeigt!
Mehrere Trainings (Radfahren outdoor) abgeschlossen. App hat Zugriff auf Health Daten. 
In Health und Aktivitäten wird dieses angezeigt. 

Die App bleibt ohne Einträge!

**Comment by andre0707** [comment]
Hallo,
wie sind denn die Filtereinstellungen in „Workout Map“ gesetzt?
Passt der eingestellte Zeitraum zu den Tagen, an denen die Trainings waren? Wurden die Aktivitäten im Filter richtig gesetzt?

in der Health/Fitness App sind Routen sichtbar?

bitte auch nochmal in der Einstellungen App > Datenschutz > Health > Workout Map prüfen, ob lesender Zugriff gestattet ist.

**Comment by andre0707** [comment]
Ich habe noch einen Hilfe-Artikel ergänzt: https://github.com/andre0707/WorkoutMap/wiki/Hilfe,-es-wird-nichts-angezeigt

**Comment by simsala** [comment]
Bei mir wird ebenfalls nix angezeigt.
Trotz massenhafter Daten und korrekten Einstellungen.
Auch die Statistik steht auf Null.
Nix. Nada.

**Comment by PiotRe36** [comment]
> Es wird leider nix angezeigt! Mehrere Trainings (Radfahren outdoor) abgeschlossen. App hat Zugriff auf Health Daten. In Health und Aktivitäten wird dieses angezeigt.
> 
> Die App bleibt ohne Einträge!

Lösung gefunden!

In der Apple Fitness App (Ringe) wurden unter Trainings keine Karten angezeigt. 
Dazu folgende Lösung: Einstellungen/ Datenschutz/ Ortungsdienste/ Apple Watch-Training/ Zugriff auf Standort erlauben/ Beim verwenden der App aktivieren. 
Jetzt werden die Strecken angezeigt und diese sind nun auch in Workout Map verfügbar. 

Gruß

**Comment by andre0707** [comment]
Super 😊
