### ISSUE TITLE
Trainingstyp "Andere" nicht vorhanden

### ISSUE THREAD

**Issue by uli-rpi** [andre0707/WorkoutMap#3]
![image](https://user-images.githubusercontent.com/84666727/158048906-569ceb51-2235-4c8a-945b-560df9226165.png)

Nutze die neueste Version mit Apple Watch.

**Comment by andre0707** [comment]
Im Filter werden nur Trainingstypen angezeigt, zu denen es auch in der Health App ein Training von diesem Typ gibt.
(Wandern ist z.B. in dem Screenshot auch nicht aufgelistet, wird aber ausgewertet)

Ist in der Health App sicher eins vom Typ „Andere“ vorhanden?

**Comment by uli-rpi** [comment]
Dann habe ich Andere falsch verstanden :), unter der Rubrik gibt es bei mir nur Händewaschen

**Comment by andre0707** [comment]
Denkbar wäre das z.B. eine iPhone App „Nordic Walking“ oder ähnliches aufzeichnen kann und das dann unter „Andere“ abspeichert, da es Nordic Walking bei Health direkt nicht zur Auswahl gibt. 
Mit der Filteroption könnten so diese Trainings mit in Workout Map angezeigt werden 😊


Workout Map zeigt dann im Filter nur die Trainingstypen an, für die auch ein Training existiert, damit die Liste nicht durch irrelevante Einträge länger wird.

**Comment by uli-rpi** [comment]
Ich würde es so designen, dass alle Aktivitäten die eine Strecke in Health aufzeichnen können im Filter auswählbar sind..
