### ISSUE TITLE
Die App friert ein, wenn der Zeitraum zu lang ist

### ISSUE THREAD

**Issue by phillipgoik** [andre0707/WorkoutMap#4]
Wenn ich versuche eine Heatmap zu erstellen über einen längeren Zeitraum dann wird die Heatmap im Grunde erstellt. Jedoch friert die App dann ein und es kann auf der Karte nicht gezoomt werden.

**Comment by andre0707** [comment]
Oh, das sollte natürlich nicht passieren. 
Was ist denn die grobe Größenordnung der Anzahl der Trainings?

**Comment by phillipgoik** [comment]
iPhone XR, iOS 16.2

**Comment by phillipgoik** [comment]
iPhone XR, iOS 16.2

Es sind ca. 700 Trainings.
Zeitraum 06/2019-heute 

wenn der Zeitraum eingeschränkt wird auf 01.01.2020-31.12.2022 648 Trainings dann ruckelt die App nach der Erzeugung der Heatmap, aber funktioniert

**Comment by andre0707** [comment]
Sind es oft wechselnde Trainingstypen in der zeitlichen Reihenfolge?
Oder sind die Trainings teilweise sehr weit auseinander, so dass die Karte extrem weit raus zoomt?


Unabhängig davon arbeite ich aktuell an einem Update. Dieses enthält unter anderem ein optimierteres Zeichnen der Routen. Tests auf einem iPhone XS Testgerät laufen mit ca. 950 Trainings bisher sehr flüssig.

**Comment by phillipgoik** [comment]
Dann wird es unter Umständen am geringeren RAM liegen.  
Es sind ausschließlich Radfahrtrainings. Aber die Map erstreckt sich von Spanien bis Norwegen, sodass weit herausgezoomt werden müsste.

**Comment by andre0707** [comment]
Das kann dann sehr gut sein. Weit raus gezoomte Karten brauchen allgemein einiges an RAM. 
Ich denke, dass es mit dem optimierteren Zeichnen dann aber trotzdem etwas besser sein sollte.

**Comment by andre0707** [comment]
Tritt das Problem mit iOS 16.4 und version 2.0 der App noch auf?

**Comment by phillipgoik** [comment]
> Tritt das Problem mit iOS 16.4 und version 2.0 der App noch auf?

Ich habe deine Antwort nicht gesehen 😱
Nein. Das rendern funktioniert ohne Absturz! :-) Vielen Lieben Dank.

Das Einzige, was mir aufgefallen ist, dass einzelne Strecken nicht mitgerendert werden. Aber da könnte es möglicherweise am Datensatz aus der Apple Watch liegen 🤷‍♂️

**Comment by phillipgoik** [comment]
> > Tritt das Problem mit iOS 16.4 und version 2.0 der App noch auf?
> 
> Ich habe deine Antwort nicht gesehen 😱
> Nein. Das rendern funktioniert ohne Absturz! :-) Vielen Lieben Dank.
> 
> Das Einzige, was mir aufgefallen ist, dass einzelne Strecken nicht mitgerendert werden. Aber da könnte es möglicherweise am Datensatz aus der Apple Watch liegen 🤷‍♂️

Ein löschen der Datenbank und neu rendern hat's gelöst. Die App ist der Hammer.

Vielen lieben Dank dafür 🙏

**Comment by andre0707** [comment]
Super, dass jetzt alles funktioniert. 
Ich schließe dann mal das Ticket hier :)
