### ISSUE TITLE
Export als Geodatei möglich?

### ISSUE THREAD

**Issue by BenKraas** [andre0707/WorkoutMap#6]
Hi Andre, 

ich würde gerne wissen ob es möglich ist die gelaufenen Strecken nach einiger Zeit als Geodatei in irgendeinem GIS-Format (.shp/.geojson/.gpkg) zu exportieren. 
Das ist zwar total nerdig und extrem spezifisch aber so kann man dann noch witzige Sachen mit QGIS etc. im Nachhinein machen. 

Interessant wäre wenn man für jeden Run zb. einen Multilinestring mit den Attributen Aufnahmebeginn (ymdhms) und Aufnahmeende (ymdhms) bekommen kann und alle Runs in ein Paket beliebigen Formates (welches ist mir total egal) packen und exportieren kann.

Ich habe die App noch nicht gekauft aber wenn solch ein Feature existiert oder kommt bin ich sofort am Start.

Das wäre ein absolutes Träumchen, sowas findet man wahrscheinlich nirgendwo sonst.

Liebe hoffnungsvolle Grüße
Ben

**Comment by andre0707** [comment]
Hallo Ben,

aktuell bietet Workout Map keinen Export der Daten in Textform an. Der Fokus liegt auf der Darstellung der Strecken auf der Karte als Bilddatei bzw. dem datensparsamen Export der Strecke auf einem eigenen Hintergrundbild ohne Ortsinformationen.

Workout Map errechnet auch eine vereinfachte Strecke jedes Trainings, da dies zum Zeichnen völlig ausreichend und vor allem performanter ist. Ich weiß nicht, ob die Daten der vereinfachten Strecke für dein Anliegen überhaupt ausreichend wären.

Ich glaube Workout Map ist auch insgesamt nicht die richtige App für dein Anliegen.


Vielleicht gibt es bereits eine andere App im AppStore, die genau das bereits erledigt. Ansonsten hilft dir eventuell auch meine kostenlose App Workout Transferer ([AppStore Link](https://apps.apple.com/de/app/workout-transferer/id1612651660)) weiter. Die ist eigentlich dazu gedacht Trainingsdaten zwischen 2 Geräten austauschen zu können. Die Datei, die für den Austausch benutzt wird, enthält aber die wichtigsten Trainingsdaten: Aktivitätsbeginn, Aktivitätsende, Aktivitätskalorien, Aktivitätstyp und alle GPS-Koordinaten (bestehend aus Timestamp, Latitude, Longitude und Altitude) die während des Trainings aufgezeichnet wurden.
Die Timestamps in der Datei sind aktuell im Cocoa Timestamp angegeben und könnten z.B. [hier](https://www.epochconverter.com/coredata) umgerechnet werden.

Workout Transferer is auch komplett Open Source auf [GitHub](https://github.com/andre0707/WorkoutTransferer) zu finden. 
Dort könnte man sicher auch noch ein anderes Exportformat ergänzen, wenn das aktuelle absolut nicht in Frage kommt.

Viele Grüße 
Andre

**Comment by BenKraas** [comment]
Hi Andre,

erstmal vielen Dank für deine ausführliche Antwort!

Ich habe mir die Workout Map App trotzdem mal geholt, alleine weil ich das Konzept total mag.
Noch habe ich es nicht geschafft mir ein Workout anzeigen zu lassen, ich glaube aber auch zu wissen warum nicht und es liegt nicht an deiner App sondern an der Kommunikation Aufzeichnungsapp => Health.

Werde damit jetzt in den nächsten Tagen rumspielen und kann gern schreiben wenn's klappt.

Der Workout Transferer wird dann wahrscheinlich genau das sein was ich suche - den schaue ich mir danach mal an.
Und was das Exportformat angeht habe ich keine Vorbehalte - solange ich das mit Python auslesen kann, sollte ich es auch schaffen das in ein .gpkg oder .shp umzuwandeln. 
Ich schätze aber mal, dass du den Code dann nicht brauchen kannst - ist ja Python, nicht Swift.

Beste Grüße
Ben

**Comment by andre0707** [comment]
Hi Ben,

da hast du Recht. Leider schreiben nicht alle Smartwatches/Apps auch die Streckeninformationen in Health. Dann kann Workout Map auch nichts auslesen/anzeigen.

Gerne, Rückmeldungen sind immer interessant. Mit welcher App zeichnest du deine Trainings auf?

Das Format vom Workout Transferer sollte ohne Probleme mit Python auslesbar sein. Das einzige Problem könnte, wie oben genannt, die Umwandlung der Timestamps sein. Falls du da ein anderes Format benötigst als das jetzige, öffne einfach ein Ticket in dem GitHub Projekt dazu. Dann kann ich das auch umstellen und ein Update der App anstoßen.

Viele Grüße
Andre

**Comment by BenKraas** [comment]
Hey Andre,

ich habe erst Runkeeper und die Adidas-App ausprobiert - ohne Erfolg, da diese Apps die Wegstrecke nicht mit Health teilen.

Mit **Strava** funktioniert es hervorragend - Deine App funktioniert jetzt exakt so wie man es erwartet :)

Das Format schaue ich mir mal in einem halben Jahr oder so an wenn ich ein paar Strecken gesammelt habe ^^
Sollte ich aber gut hinkriegen.

Vielen Dank und viele Grüße
Ben

**Comment by andre0707** [comment]
Hi Ben, 

danke für die Rückmeldung.

Falls du dann Fragen zu dem Format hast, melde dich einfach. 

Viele Grüße
Andre
