### ISSUE TITLE
Feature request: export GPX files in order to use them in other applications

### ISSUE THREAD

**Issue by jan-eckhoff** [andre0707/WorkoutMap#8]
Hi,

would it be possible to use WorkoutMap as a way to export the GPX tracks directly and filtered (by activity, date range, ...), rather than having to go through Apple's Health Data Export, where you end up with a pile of unfiltered GPX tracks?

Best,
Jan

**Comment by andre0707** [comment]
Hi Jan, 

are you thinking about a special gpx track format for the export file? Special names for the gps tags or any special formatting for the timestamp of each gpx point?

**Comment by jan-eckhoff** [comment]
Hi, not really. I was thinking I get one GPX per workout, for all the workouts I have selected (e.g. all cycling workouts for all of 2023), packed up in a handy ZIP file. The format wouldn't have to change from what Apple would otherwise give me in their Health Data Export.

It's also quite possible that WorkoutTransferer would be the better tool to provide this functionality 🤔

**Comment by andre0707** [comment]
I will have to look into the export file format from the health app. But I generally agree on WorkoutTransferer being the better app for such a feature.
Also, Workout Map only shows and caches a simplified route of each workout due to performance reasons. An export from there would not include all recorded gps track points during the workout.

**Comment by andre0707** [comment]
How exactly did you export from the Health app?
Are you talking about the complete export of all health data?

**Comment by jan-eckhoff** [comment]
Yup, exactly.





Gesendet von unterwegs.

Am 04.01.2024 um 13:05 schrieb Andre ***@***.***>:




﻿

How exactly did you export from the Health app?
Are you talking about the complete export of all health data?
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by andre0707** [comment]
I decided to add this as a feature to **Workout Transferer**. Feels like a better fit for me than here and I generally like the addition. I also just added the feature request in the other repository and will close this one here. See [https://github.com/andre0707/WorkoutTransferer/issues/1](https://github.com/andre0707/WorkoutTransferer/issues/1).

I think I can finish a first draft of the feature this weekend. If you are interested in testing via **TestFlight** beta testing, please answer in the other ticket at: [https://github.com/andre0707/WorkoutTransferer/issues/1](https://github.com/andre0707/WorkoutTransferer/issues/1)
