### ISSUE TITLE
Feature Request: Blauer Punkt/Live Standort

### ISSUE THREAD

**Issue by dergreg** [andre0707/WorkoutMap#9]
Hi Andre,

super App hast du da entwickelt, es macht Spaß die Kacheln auch in der näheren Umgebung nach und nach zu füllen.

Dafür fehlt mir eine Kleinigkeit als "Convenience": Wenn man auf das Pfeil-Icon klickt, um den aktuellen Standort zu zentrieren wäre es super, wenn man einen blauen Punkt wie bei Apple Maps/Google Maps hätte. Aktuell ist es schwer zu erkennen, wo man sich befindet.

Optimal wäre es, wenn man den aktuellen Standort live verfolgen könnte.

**Comment by andre0707** [comment]
Hey, vielen Dank für das Feedback!

Wenn es dir rein um die Kacheln geht, schau dir doch mal [Tiles Explorer im AppStore](https://apps.apple.com/de/app/tiles-explorer/id1644377418) an. Das ist darauf quasi optimiert neue Tiles zu besuchen.
Man kann sich Tiles als Favoriten markieren (die man gerne als Nächstes besuchen möchte) und auch einen Marker auf der Karte setzen, um die Distanz zu sehen oder sich dorthin navigieren zu lassen. Man kann sich auch ganz konkret die noch nicht besuchten Tiles nur anzeigen lassen (Zoomstufe beachten) und es gibt auch die Möglichkeit die OpenStreetmap (oder eine andere) Karte zu nutzen. Das macht es manchmal bei Feld- und Waldwegen einfacher. Eine kleine Übersichtsstatistik mit den besuchten Tiles ist auch dabei.
Man sieht die Tiles auch besser, wenn nicht noch die besuchten Routen mit im Bild sind.
Die besuchten Kacheln werden mit WorkoutMap abgeglichen, so dass man seine Workouts nicht 2x analysieren muss.

Für Workout Map selbst sehe ich den Standortpunkt bisher eher etwas störend an, da der Fokus auf den zurückgelegten Strecken liegen soll. Werde die Anmerkung aber mal für ein zukünftiges Update mit aufnehmen, wenn dir die Option über Tiles Explorer gar nicht zusagt.

Viele Grüße 
Andre

**Comment by dergreg** [comment]
Sorry für die späte Rückmeldung. Ja das passt für mich, dass das separat über den Tiles Explorer läuft. 🙂

Danke für die kleinen praktischen Apps!
